#include "windowsMessageLog.hpp"
#include <iomanip>
#include <sstream>

const std::unordered_map<UINT , const char * > windowsMessageLog::map = 
{
	GET_MESSAGE(WM_CREATE),
	GET_MESSAGE(WM_DESTROY),
	GET_MESSAGE(WM_MOVE),
	GET_MESSAGE(WM_SIZE),
	GET_MESSAGE(WM_SETFOCUS),
	GET_MESSAGE(WM_KILLFOCUS),
	GET_MESSAGE(WM_ENABLE),
	GET_MESSAGE(WM_SETREDRAW),
	GET_MESSAGE(WM_SETTEXT),
	GET_MESSAGE(WM_GETTEXT),
	GET_MESSAGE(WM_GETTEXTLENGTH),
	GET_MESSAGE(WM_PAINT),
	GET_MESSAGE(WM_CLOSE),
	GET_MESSAGE(WM_QUERYENDSESSION),
	GET_MESSAGE(WM_QUIT),
	GET_MESSAGE(WM_ERASEBKGND),
	GET_MESSAGE(WM_SYSCOLORCHANGE),
	GET_MESSAGE(WM_SHOWWINDOW),
	GET_MESSAGE(WM_WININICHANGE),
	GET_MESSAGE(WM_SETTINGCHANGE),
	GET_MESSAGE(WM_DEVMODECHANGE),
	GET_MESSAGE(WM_ACTIVATEAPP),
	GET_MESSAGE(WM_FONTCHANGE),
	GET_MESSAGE(WM_TIMECHANGE),
	GET_MESSAGE(WM_CANCELMODE),
	GET_MESSAGE(WM_SETCURSOR),
	GET_MESSAGE(WM_MOUSEACTIVATE),
	GET_MESSAGE(WM_CHILDACTIVATE),
	GET_MESSAGE(WM_QUEUESYNC),
	GET_MESSAGE(WM_KEYDOWN),
	GET_MESSAGE(WM_KEYUP),
	GET_MESSAGE(WM_CHAR),
	GET_MESSAGE(WM_DEADCHAR),
	GET_MESSAGE(WM_SYSKEYDOWN),
	GET_MESSAGE(WM_SYSKEYUP),
	GET_MESSAGE(WM_SYSCHAR),
	GET_MESSAGE(WM_SYSDEADCHAR),
	GET_MESSAGE(WM_INITDIALOG),
	GET_MESSAGE(WM_COMMAND),
	GET_MESSAGE(WM_SYSCOMMAND),
	GET_MESSAGE(WM_TIMER),
	GET_MESSAGE(WM_HSCROLL),
	GET_MESSAGE(WM_VSCROLL),
	GET_MESSAGE(WM_INITMENU),
	GET_MESSAGE(WM_INITMENUPOPUP),
	GET_MESSAGE(WM_GESTURE),
	GET_MESSAGE(WM_GESTURENOTIFY),
	GET_MESSAGE(WM_TOUCH),
	GET_MESSAGE(WM_MOUSEMOVE),
	GET_MESSAGE(WM_LBUTTONDOWN),
	GET_MESSAGE(WM_LBUTTONUP),
	GET_MESSAGE(WM_RBUTTONDOWN),
	GET_MESSAGE(WM_RBUTTONUP),
	GET_MESSAGE(WM_MBUTTONDOWN),
	GET_MESSAGE(WM_MBUTTONUP),
	GET_MESSAGE(WM_MOUSEWHEEL),
	GET_MESSAGE(WM_PARENTNOTIFY),
	GET_MESSAGE(WM_MDIACTIVATE),
	GET_MESSAGE(WM_MDICREATE),
	GET_MESSAGE(WM_MDIDESTROY),
	GET_MESSAGE(WM_MDIRESTORE),
	GET_MESSAGE(WM_MDIREFRESHMENU),
	GET_MESSAGE(WM_MDITILE),
	GET_MESSAGE(WM_MDICASCADE),
	GET_MESSAGE(WM_MDIICONARRANGE),
	GET_MESSAGE(WM_QUERYNEWPALETTE),
	GET_MESSAGE(WM_PALETTEISCHANGING),
	GET_MESSAGE(WM_PALETTECHANGED),
	GET_MESSAGE(WM_DROPFILES),
	GET_MESSAGE(WM_DRAWCLIPBOARD),
	GET_MESSAGE(WM_PAINTCLIPBOARD),
	GET_MESSAGE(WM_VSCROLLCLIPBOARD),
	GET_MESSAGE(WM_SIZECLIPBOARD),
	GET_MESSAGE(WM_ASKCBFORMATNAME),
	GET_MESSAGE(WM_CHANGECBCHAIN),
	GET_MESSAGE(WM_HSCROLLCLIPBOARD),
	GET_MESSAGE(WM_QUERYUISTATE),
	GET_MESSAGE(WM_UPDATEUISTATE),
	GET_MESSAGE(WM_NOTIFY),
	GET_MESSAGE(WM_INPUTLANGCHANGEREQUEST),
	GET_MESSAGE(WM_INPUTLANGCHANGE),
	GET_MESSAGE(WM_TCARD),
	GET_MESSAGE(WM_HELP),
	GET_MESSAGE(WM_USERCHANGED),
	GET_MESSAGE(WM_NOTIFYFORMAT),
	GET_MESSAGE(WM_CONTEXTMENU),
	GET_MESSAGE(WM_STYLECHANGING),
	GET_MESSAGE(WM_STYLECHANGED),
	GET_MESSAGE(WM_DISPLAYCHANGE),
	GET_MESSAGE(WM_GETICON),
	GET_MESSAGE(WM_SETICON),
	GET_MESSAGE(WM_NCCREATE),
	GET_MESSAGE(WM_NCDESTROY),
	GET_MESSAGE(WM_NCCALCSIZE),
	GET_MESSAGE(WM_NCHITTEST),
	GET_MESSAGE(WM_NCPAINT),
	GET_MESSAGE(WM_NCACTIVATE),
	GET_MESSAGE(WM_NCMOUSEMOVE),
	GET_MESSAGE(WM_NCLBUTTONDOWN),
	GET_MESSAGE(WM_NCLBUTTONUP),
	GET_MESSAGE(WM_NCLBUTTONDBLCLK),
	GET_MESSAGE(WM_NCRBUTTONDOWN),
	GET_MESSAGE(WM_NCRBUTTONUP),
	GET_MESSAGE(WM_NCRBUTTONDBLCLK),
	GET_MESSAGE(WM_NCMBUTTONDOWN),
	GET_MESSAGE(WM_NCMBUTTONUP),
	GET_MESSAGE(WM_NCMBUTTONDBLCLK),
	GET_MESSAGE(WM_NCXBUTTONDOWN),
	GET_MESSAGE(WM_NCXBUTTONUP),
	GET_MESSAGE(WM_NCXBUTTONDBLCLK),
};

void windowsMessageLog::get_str(std::wstring& in, const UINT msg, const WPARAM wParam, const LPARAM lParam) const {

	const int ColumnWidth = 25;
	const auto it = map.find(msg);

	std::ostringstream oss;

	if (it != map.end()) {
		oss << std::left << std::setw(ColumnWidth) << it->second << std::right;
	}
	else {
		oss << std::left << std::setw(ColumnWidth) << std::hex << msg << std::right;
	}

	oss << " WPARAM: " << std::hex << std::setw(8) << wParam
		<< " LPARAM: " << std::hex << std::setw(8) << lParam;

	oss << std::endl << std::dec;

	std::string str = oss.str();
	in = std::wstring(str.begin(), str.end());
}
